services:
  # One-shot init: grants permissions on shared folders
  init-dirs:
    container_name: udata-frontend-init-dirs
    image: busybox:stable
    command: sh -c "chown -R ${NEXTJS_UID:-10001}:${NEXTJS_GID:-10001} /logs /cache && chmod 2775 /logs /cache"
    volumes:
      - ./logs:/logs
      - ./.next/cache:/cache
    networks:
      - api_tabular_network

  app:
    container_name: data-explorer-app
    depends_on:
      init-dirs:
        condition: service_completed_successfully
    build:
      context: .
      args:
        NEXTJS_UID: ${NEXTJS_UID:-10001}
        NEXTJS_GID: ${NEXTJS_GID:-10001}
        TABULAR_API_URL: api-tabular-pt-tabular-api-1:8005
    command: sh -c "node server.js 2>&1 | tee -a /logs/app.log"
    init: true
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/logs
    environment:
      # link to Tabular API
      TABULAR_API_URL: api-tabular-pt-tabular-api-1:8005
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - api_tabular_network

# the network where the API is running
networks:
  api_tabular_network:
    external: true
    name: api-tabular-pt_default
